config/routes.rb
Rails.application.routes.draw do

  resources :movements
  resources :goals
  resources :warranties
  resources :concepts
  resources :accounts 
  
  devise_for :users, controllers: {
    sessions: 'users/sessions', 
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'home#index'
  
  get 'main', to: 'home#dashboard', as: 'dashboard' 
  get 'mi_familia/:id', to: 'familia#mi_familia', as: 'mi_familia' 
  
  
end

app/models/warranty.rb
class Warranty < ApplicationRecord
  belongs_to :user
end

app/controllers/warranties_controller.rb
class WarrantiesController < ApplicationController
  before_action :set_warranty, only: %i[ show edit update destroy ]

  # GET /warranties or /warranties.json
  def index
    @warranties = Warranty.all
  end

  # GET /warranties/1 or /warranties/1.json
  def show
  end

  # GET /warranties/new
  def new
    @warranty = Warranty.new
  end

  # GET /warranties/1/edit
  def edit
  end

  # POST /warranties or /warranties.json
  def create
    @warranty = Warranty.new(warranty_params)

    respond_to do |format|
      if @warranty.save
        format.html { redirect_to warranty_url(@warranty), notice: "Warranty was successfully created." }
        format.json { render :show, status: :created, location: @warranty }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @warranty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /warranties/1 or /warranties/1.json
  def update
    respond_to do |format|
      if @warranty.update(warranty_params)
        format.html { redirect_to warranty_url(@warranty), notice: "Warranty was successfully updated." }
        format.json { render :show, status: :ok, location: @warranty }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @warranty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /warranties/1 or /warranties/1.json
  def destroy
    @warranty.destroy

    respond_to do |format|
      format.html { redirect_to warranties_url, notice: "Warranty was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_warranty
      @warranty = Warranty.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def warranty_params
      params.require(:warranty).permit(:nombre, :no_identificacion, :fecha_adq, :estado, :periodo_dias, :dias_restantes, :user_id)
    end
end

app/helpers/warranties_helper.rb
module WarrantiesHelper
end

app/views/warranties/_form.html.erb
<%= form_with(model: warranty, local: true) do |form| %>
  <% if warranty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(warranty.errors.count, "error") %> prohibited this warranty from being saved:</h2>

      <ul>
        <% warranty.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :no_identificacion %>
    <%= form.text_field :no_identificacion %>
  </div>

  <div class="field">
    <%= form.label :fecha_adq %>
    <%= form.date_select :fecha_adq %>
  </div>

  <div class="field">
    <%= form.label :estado %>
    <%= form.text_field :estado %>
  </div>

  <div class="field">
    <%= form.label :periodo_dias %>
    <%= form.number_field :periodo_dias %>
  </div>

  <div class="field">
    <%= form.label :dias_restantes %>
    <%= form.number_field :dias_restantes %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/warranties/edit.html.erb
<h1>Editing Warranty</h1>

<%= render 'form', warranty: @warranty %>

<%= link_to 'Show', @warranty %> |
<%= link_to 'Back', warranties_path %>

app/views/warranties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Warranties</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>No identificacion</th>
      <th>Fecha adq</th>
      <th>Estado</th>
      <th>Periodo dias</th>
      <th>Dias restantes</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @warranties.each do |warranty| %>
      <tr>
        <td><%= warranty.nombre %></td>
        <td><%= warranty.no_identificacion %></td>
        <td><%= warranty.fecha_adq %></td>
        <td><%= warranty.estado %></td>
        <td><%= warranty.periodo_dias %></td>
        <td><%= warranty.dias_restantes %></td>
        <td><%= warranty.user_id %></td>
        <td><%= link_to 'Show', warranty %></td>
        <td><%= link_to 'Edit', edit_warranty_path(warranty) %></td>
        <td><%= link_to 'Destroy', warranty, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Warranty', new_warranty_path %>

app/views/warranties/new.html.erb
<h1>New Warranty</h1>

<%= render 'form', warranty: @warranty %>

<%= link_to 'Back', warranties_path %>

app/views/warranties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @warranty.nombre %>
</p>

<p>
  <strong>No identificacion:</strong>
  <%= @warranty.no_identificacion %>
</p>

<p>
  <strong>Fecha adq:</strong>
  <%= @warranty.fecha_adq %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @warranty.estado %>
</p>

<p>
  <strong>Periodo dias:</strong>
  <%= @warranty.periodo_dias %>
</p>

<p>
  <strong>Dias restantes:</strong>
  <%= @warranty.dias_restantes %>
</p>

<p>
  <strong>User:</strong>
  <%= @warranty.user_id %>
</p>

<%= link_to 'Edit', edit_warranty_path(@warranty) %> |
<%= link_to 'Back', warranties_path %>