config/routes.rb
Rails.application.routes.draw do

  resources :movements
  resources :goals
  resources :warranties
  resources :concepts
  resources :accounts 
  
  devise_for :users, controllers: {
    sessions: 'users/sessions', 
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'home#index'
  
  get 'main', to: 'home#dashboard', as: 'dashboard' 
  get 'mi_familia/:id', to: 'familia#mi_familia', as: 'mi_familia' 
  
  
end

app/models/concept.rb
class Concept < ApplicationRecord

    def guardar_concept(usuario)
      self.user_id = usuario.id
      if self.save
        self
      else
        nil
      end
      
    end

    def self.conceptos_familiares(family_id)
      #consulta para traer todos los usuarios de una familia 
      #select * from users where family_id = [family_id]
      usuarios = User.where(family_id: family_id)
      if usuarios
        #consulta para optener los conceptos de los usuarios optenidos 
        Concept.where(user_id: usuarios)
      else
        nil
      end

    end

end

app/controllers/concepts_controller.rb
class ConceptsController < ApplicationController
  before_action :set_concept, only: %i[ show edit update destroy ]

  # GET /concepts or /concepts.json
  def index
    @concepts = Concept.all
  end

  # GET /concepts/1 or /concepts/1.json
  def show
  end

  # GET /concepts/new
  def new
    @concept = Concept.new
  end

  # GET /concepts/1/edit
  def edit
  end

  # POST /concepts or /concepts.json
  def create
    @concept = Concept.new(concept_params)
    concepto = @concept.guardar_concept(current_user)

    respond_to do |format|
      if concepto
        format.html { redirect_to concept_url(@concept), notice: "Concept was successfully created." }
        format.json { render :show, status: :created, location: @concept }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @concept.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /concepts/1 or /concepts/1.json
  def update
    respond_to do |format|
      if @concept.update(concept_params)
        format.html { redirect_to concept_url(@concept), notice: "Concept was successfully updated." }
        format.json { render :show, status: :ok, location: @concept }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @concept.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concepts/1 or /concepts/1.json
  def destroy
    @concept.destroy

    respond_to do |format|
      format.html { redirect_to concepts_url, notice: "Concept was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_concept
      @concept = Concept.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def concept_params
      params.require(:concept).permit(:nombre, :tipo, :descripcion, :user_id)
    end
end

app/helpers/concepts_helper.rb
module ConceptsHelper
end

app/views/concepts/_form.html.erb
<%= form_with(model: concept, local: true) do |form| %>
  <% if concept.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(concept.errors.count, "error") %> prohibited this concept from being saved:</h2>

      <ul>
        <% concept.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :tipo %>
    <%= form.number_field :tipo %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion %>
  </div>

  <!-- <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div> -->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/concepts/edit.html.erb
<h1>Editing Concept</h1>

<%= render 'form', concept: @concept %>

<%= link_to 'Show', @concept %> |
<%= link_to 'Back', concepts_path %>

app/views/concepts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Concepts</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Tipo</th>
      <th>Descripcion</th>
      <!-- <th>User</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @concepts.each do |concept| %>
      <tr>
        <td><%= concept.nombre %></td>
        <td><%= concept.tipo %></td>
        <td><%= concept.descripcion %></td>
        <!--<td><%= concept.user_id %></td> -->
        <td><%= link_to 'Show', concept %></td>
        <td><%= link_to 'Edit', edit_concept_path(concept) %></td>
        <td><%= link_to 'Destroy', concept, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Concept', new_concept_path %>

app/views/concepts/new.html.erb
<h1>New Concept</h1>

<%= render 'form', concept: @concept %>

<%= link_to 'Back', concepts_path %>

app/views/concepts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @concept.nombre %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @concept.tipo %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @concept.descripcion %>
</p>

<!--
<p>
  <strong>User:</strong>
  <%= @concept.user_id %>
</p> -->

<%= link_to 'Edit', edit_concept_path(@concept) %> |
<%= link_to 'Back', concepts_path %>