config/routes.rb
Rails.application.routes.draw do

  resources :movements
  resources :goals
  resources :warranties
  resources :concepts
  resources :accounts 
  
  devise_for :users, controllers: {
    sessions: 'users/sessions', 
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'home#index'
  
  get 'main', to: 'home#dashboard', as: 'dashboard' 
  get 'mi_familia/:id', to: 'familia#mi_familia', as: 'mi_familia' 
  
  
end

app/models/account.rb
class Account < ApplicationRecord

    def guardar_cuenta(usuario)
        #cuenta = Account.new(user_id: usuario.id, nombre: nombre, descripcion: descripcion, saldo: saldo, tipo_cuenta: tipo_cuenta, tipo_familiar: tipo_familiar)
        self.user_id = usuario.id
        if self.save
            self
        else
            nil
        end
        
    end
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concept.rb
class Concept < ApplicationRecord

    def guardar_concept(usuario)
      self.user_id = usuario.id
      if self.save
        self
      else
        nil
      end
      
    end

    def self.conceptos_familiares(family_id)
      #consulta para traer todos los usuarios de una familia 
      #select * from users where family_id = [family_id]
      usuarios = User.where(family_id: family_id)
      if usuarios
        #consulta para optener los conceptos de los usuarios optenidos 
        Concept.where(user_id: usuarios)
      else
        nil
      end

    end

end

app/models/family.rb
class Family < ApplicationRecord
  belongs_to :user
end

app/models/goal.rb
class Goal < ApplicationRecord
    
    def guardar_metas(usuario)
      self.user_id = usuario.id
      self.family_id = usuario.family_id
      if self.save
          self
      else
          nil
      end
    end

end


#belongs_to :family
  #belongs_to :user
  

app/models/movement.rb
class Movement < ApplicationRecord

  def guardad_movimientos(usuario)
      self.user_id = usuario.id
      if self.save
          self
      else
          nil
      end

      end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable , :confirmable , :trackable

  before_save :asignar_tipo

  protected

  def asignar_tipo
    if !self.family_id
      self.tipo_usuario = 1
    end
    

  end
end

app/models/warranty.rb
class Warranty < ApplicationRecord
  belongs_to :user
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: %i[ show edit update destroy ]
  before_action :authenticate_user! 

  # GET /accounts or /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1 or /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts or /accounts.json
  def create
    @account = Account.new(account_params)
    cuenta = @account.guardar_cuenta(current_user)

    respond_to do |format|
      if cuenta
        format.html { redirect_to accounts_path, notice: "Account was successfully created." }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1 or /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to account_url(@account), notice: "Account was successfully updated." }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1 or /accounts/1.json
  def destroy
    @account.destroy

    respond_to do |format|
      format.html { redirect_to accounts_url, notice: "Account was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def account_params
      params.require(:account).permit(:nombre, :descripcion, :saldo, :tipo_cuenta, :tipo_familiar, :user_id)
    end
end

app/controllers/familia_controller.rb
class FamiliaController < ApplicationController
  
    def mi_familia
        
    end
    
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: %i[ show edit update destroy ]

  # GET /goals or /goals.json
  def index
    @goals = Goal.all
  end

  # GET /goals/1 or /goals/1.json
  def show
  end

  # GET /goals/new
  def new
    @goal = Goal.new
  end

  # GET /goals/1/edit
  def edit
  end

  # POST /goals or /goals.json
  def create
    @goal = Goal.new(goal_params)
    goal = @goal.guardar_metas(current_user)

    respond_to do |format|
      if goal
        format.html { redirect_to goal_url(@goal), notice: "Goal was successfully created." }
        format.json { render :show, status: :created, location: @goal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goals/1 or /goals/1.json
  def update
    respond_to do |format|
      if @goal.update(goal_params)
        format.html { redirect_to goal_url(@goal), notice: "Goal was successfully updated." }
        format.json { render :show, status: :ok, location: @goal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1 or /goals/1.json
  def destroy
    @goal.destroy

    respond_to do |format|
      format.html { redirect_to goals_url, notice: "Goal was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal
      @goal = Goal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def goal_params
      params.require(:goal).permit(:nombre, :descripcion, :cantidad, :saldo, :family_id, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    layout 'publica', only: [:index]

    def index

    end 

    def dashboard
        
    end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/concepts_helper.rb
module ConceptsHelper
end

app/helpers/familia_helper.rb
module FamiliaHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movements_helper.rb
module MovementsHelper
end

app/helpers/warranties_helper.rb
module WarrantiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  
    <title>Proyecto</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <h1>Privada</h1>
      <div>
          <h2>Menu</h2>
          <ul>
              <li>
                <%= link_to('Inicio', dashboard_path) %>
              </li>
              <li>
                <%= link_to('Conceptos', concepts_path) %>
              </li>
              <li>
                <%= link_to('Mis metas', goals_path) %>
              </li>
              <li>
                <%= link_to('Mis Cuentas', accounts_path) %>
              </li>
              <li>
                <%= link_to('Mi Familia', mi_familia_path(current_user.family_id)) %>
              </li>
              <li>
                <%= link_to('Mis Movimientos', movements_path) %>
              </li>
              
          </ul>
      </div>
       <%= link_to('salir', destroy_user_session_path, method: :delete) if current_user%>
       <p class="notice"><%= notice if notice %></p>
       <p class="alert"><%= alert if alert %></p>

    <%= yield %>
  </body>
</html>

app/views/layouts/publica.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proyecto</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
        <h1>Publica</h1>
       <%= link_to('salir', destroy_user_session_path, method: :delete) if current_user%>
       <p class="notice"><%= notice if notice %></p>
       <p class="alert"><%= alert if alert %></p>
    <%= yield %>
  </body>
</html>